const ACTIONS = {
  INIT_BLOGS: 'INIT_BLOGS',
  CREATE_BLOG: 'CREATE_BLOG',
  UPDATE_BLOG: 'UPDATE_BLOG',
  DELETE_BLOG: 'DELETE_BLOG',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  GET_USERS: 'GET_USERS',
  CLEAR_ALERT: 'CLEAR_ALERT',
  SET_ALERT: 'SET_ALERT',
  CONFIRM_ACTION: 'CONFIRM_ACTION',
  CANCEL_ACTION: 'CANCEL_ACTION',
  ADD_COMMENT: 'ADD_COMMENT'
}

export default ACTIONS